-- tab size is 4
-- registrations for media from the client itself belongs in LibSharedMedia-3.0

local LSM = LibStub("LibSharedMedia-3.0")
local koKR, ruRU, zhCN, zhTW, western = LSM.LOCALE_BIT_koKR, LSM.LOCALE_BIT_ruRU, LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western

local MediaType_BACKGROUND = LSM.MediaType.BACKGROUND
local MediaType_BORDER = LSM.MediaType.BORDER
local MediaType_FONT = LSM.MediaType.FONT
local MediaType_STATUSBAR = LSM.MediaType.STATUSBAR 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register(MediaType_BACKGROUND, "Moo", [[Interface\Addons\SharedMedia\background\moo.tga]])
LSM:Register(MediaType_BACKGROUND, "Bricks", [[Interface\Addons\SharedMedia\background\bricks.tga]])
LSM:Register(MediaType_BACKGROUND, "Brushed Metal", [[Interface\Addons\SharedMedia\background\brushedmetal.tga]])
LSM:Register(MediaType_BACKGROUND, "Copper", [[Interface\Addons\SharedMedia\background\copper.tga]])
LSM:Register(MediaType_BACKGROUND, "Smoke", [[Interface\Addons\SharedMedia\background\smoke.tga]])
LSM:Register(MediaType_BACKGROUND, "Naowh Arrow", [[Interface\Addons\SharedMedia\background\NaowhArrow.tga]])
LSM:Register(MediaType_BACKGROUND, "Naowh Glow", [[Interface\Addons\SharedMedia\background\NaowhGlow.tga]])
LSM:Register(MediaType_BACKGROUND, "Naowh Arrow Left", [[Interface\Addons\SharedMedia\background\NaowhArrowLeft.tga]])
LSM:Register(MediaType_BACKGROUND, "Naowh Arrow Right", [[Interface\Addons\SharedMedia\background\NaowhArrowRight.tga]])
LSM:Register(MediaType_BACKGROUND, "Naowh Arrow Glow", [[Interface\Addons\SharedMedia\background\arrow_glow.tga]])

-- ----- 
--  BORDER 
-- ---- 
LSM:Register(MediaType_BORDER, "RothSquare", [[Interface\Addons\SharedMedia\border\roth.tga]])
LSM:Register(MediaType_BORDER, "SeerahScalloped", [[Interface\Addons\SharedMedia\border\SeerahScalloped.blp]])
LSM:Register(MediaType_BORDER, "Naowh1", [[Interface\Addons\SharedMedia\border\Naowh1.tga]])
LSM:Register(MediaType_BORDER, "Naowh2", [[Interface\Addons\SharedMedia\border\Naowh2.tga]])
LSM:Register(MediaType_BORDER, "Naowh3", [[Interface\Addons\SharedMedia\border\Naowh3.tga]])

-- -----
--   FONT
-- -----
LSM:Register(MediaType_FONT, "Adventure",					[[Interface\Addons\SharedMedia\font\adventure\Adventure.ttf]])
LSM:Register(MediaType_FONT, "All Hooked Up",				[[Interface\Addons\SharedMedia\font\all_hooked_up\HookedUp.ttf]])
LSM:Register(MediaType_FONT, "Bazooka",						[[Interface\Addons\SharedMedia\font\bazooka\Bazooka.ttf]])
LSM:Register(MediaType_FONT, "Black Chancery",				[[Interface\Addons\SharedMedia\font\black_chancery\BlackChancery.ttf]])
LSM:Register(MediaType_FONT, "Celestia Medium Redux",		[[Interface\Addons\SharedMedia\font\celestia_medium_redux\CelestiaMediumRedux1.55.ttf]])
LSM:Register(MediaType_FONT, "DejaVu Sans",					[[Interface\Addons\SharedMedia\font\deja_vu\DejaVuLGCSans.ttf]],							ruRU + western)
LSM:Register(MediaType_FONT, "DejaVu Serif",				[[Interface\Addons\SharedMedia\font\deja_vu\DejaVuLGCSerif.ttf]],							ruRU + western)
LSM:Register(MediaType_FONT, "DorisPP",						[[Interface\Addons\SharedMedia\font\doris_pp\DorisPP.ttf]])
LSM:Register(MediaType_FONT, "Enigmatic",					[[Interface\Addons\SharedMedia\font\enigmatic\EnigmaU_2.ttf]])
LSM:Register(MediaType_FONT, "Fitzgerald",					[[Interface\Addons\SharedMedia\font\fitzgerald\Fitzgerald.ttf]])
LSM:Register(MediaType_FONT, "Gentium Plus",				[[Interface\Addons\SharedMedia\font\gentium_plus\GentiumPlus-R.ttf]],						ruRU + western)
LSM:Register(MediaType_FONT, "Hack",						[[Interface\Addons\SharedMedia\font\hack\Hack-Regular.ttf]])
LSM:Register(MediaType_FONT, "Liberation Sans",				[[Interface\Addons\SharedMedia\font\liberation\LiberationSans-Regular.ttf]],				ruRU + western)
LSM:Register(MediaType_FONT, "Liberation Serif",			[[Interface\Addons\SharedMedia\font\liberation\LiberationSerif-Regular.ttf]],				ruRU + western)
LSM:Register(MediaType_FONT, "SF Atarian System",			[[Interface\Addons\SharedMedia\font\sf_atarian_system\SFAtarianSystem.ttf]])
LSM:Register(MediaType_FONT, "SF Covington",				[[Interface\Addons\SharedMedia\font\sf_covington\SFCovington.ttf]])
LSM:Register(MediaType_FONT, "SF Movie Poster",				[[Interface\Addons\SharedMedia\font\sf_movie_poster\SFMoviePoster-Bold.ttf]])
LSM:Register(MediaType_FONT, "SF Wonder Comic",				[[Interface\Addons\SharedMedia\font\sf_wonder_comic\SFWonderComic.ttf]])
LSM:Register(MediaType_FONT, "swf!t",						[[Interface\Addons\SharedMedia\font\swf!t\SWF!T___.ttf]])
LSM:Register(MediaType_FONT, "WenQuanYi Zen Hei",			[[Interface\Addons\SharedMedia\font\wen_quan_yi_zen_hei\wqy-zenhei.ttf]],					koKR + ruRU + zhCN + zhTW + western)
LSM:Register(MediaType_FONT, "Yellowjacket",				[[Interface\Addons\SharedMedia\font\yellowjacket\yellow.ttf]])
LSM:Register("font", "Naowh", [[Interface\Addons\SharedMedia\font\Naowh.ttf]],					ruRU + western) 
LSM:Register("font", "GothamNarrowUltra", [[Interface\Addons\SharedMedia\font\GothamNarrowUltra.ttf]],					ruRU + western)
LSM:Register(MediaType_FONT, "Raleway Regular",					[[Interface\Addons\SharedMedia\font\Raleway-Regular.ttf]])
LSM:Register(MediaType_FONT, "Raleway Medium",					[[Interface\Addons\SharedMedia\font\Raleway-Medium.ttf]])
LSM:Register(MediaType_FONT, "Raleway SemiBold",					[[Interface\Addons\SharedMedia\font\Raleway-SemiBold.ttf]])

-- -----
--   SOUND
-- -----
LSM:Register("sound", "|cff0091ed1 -Naowh|r", [[Interface\Addons\SharedMedia\sound\1 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed2 -Naowh|r", [[Interface\Addons\SharedMedia\sound\2 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed3 -Naowh|r", [[Interface\Addons\SharedMedia\sound\3 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed4 -Naowh|r", [[Interface\Addons\SharedMedia\sound\4 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed5 -Naowh|r", [[Interface\Addons\SharedMedia\sound\5 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed6 -Naowh|r", [[Interface\Addons\SharedMedia\sound\6 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed7 -Naowh|r", [[Interface\Addons\SharedMedia\sound\7 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed8 -Naowh|r", [[Interface\Addons\SharedMedia\sound\8 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed9 -Naowh|r", [[Interface\Addons\SharedMedia\sound\9 -Naowh.ogg]])
LSM:Register("sound", "|cff0091ed10 -Naowh|r", [[Interface\Addons\SharedMedia\sound\10 -Naowh.ogg]])
LSM:Register("sound", "|cff0091edAdd -Naowh|r", [[Interface\Addons\SharedMedia\sound\Add -Naowh.ogg]])
LSM:Register("sound", "|cff0091edAdds -Naowh|r", [[Interface\Addons\SharedMedia\sound\Adds -Naowh.ogg]])
LSM:Register("sound", "|cff0091edAoE -Naowh|r", [[Interface\Addons\SharedMedia\sound\AoE -Naowh.ogg]])
LSM:Register("sound", "|cff0091edAvoid -Naowh|r", [[Interface\Addons\SharedMedia\sound\Avoid -Naowh.ogg]])
LSM:Register("sound", "|cff0091edBait -Naowh|r", [[Interface\Addons\SharedMedia\sound\Bait -Naowh.ogg]])
LSM:Register("sound", "|cff0091edBehind -Naowh|r", [[Interface\Addons\SharedMedia\sound\Behind -Naowh.ogg]])
LSM:Register("sound", "|cff0091edBloodlust -Naowh|r", [[Interface\Addons\SharedMedia\sound\Bloodlust -Naowh.ogg]])
LSM:Register("sound", "|cff0091edBuff -Naowh|r", [[Interface\Addons\SharedMedia\sound\Buff -Naowh.ogg]])
LSM:Register("sound", "|cff0091edCC -Naowh|r", [[Interface\Addons\SharedMedia\sound\CC -Naowh.ogg]])
LSM:Register("sound", "|cff0091edClear In -Naowh|r", [[Interface\Addons\SharedMedia\sound\Clear In -Naowh.ogg]])
LSM:Register("sound", "|cff0091edClear -Naowh|r", [[Interface\Addons\SharedMedia\sound\Clear -Naowh.ogg]])
LSM:Register("sound", "|cff0091edCollect -Naowh|r", [[Interface\Addons\SharedMedia\sound\Collect -Naowh.ogg]])
LSM:Register("sound", "|cff0091edCombat -Naowh|r", [[Interface\Addons\SharedMedia\sound\Combat -Naowh.ogg]])
LSM:Register("sound", "|cff0091edDance -Naowh|r", [[Interface\Addons\SharedMedia\sound\Dance -Naowh.ogg]])
LSM:Register("sound", "|cff0091edDebuff -Naowh|r", [[Interface\Addons\SharedMedia\sound\Debuff -Naowh.ogg]])
LSM:Register("sound", "|cff0091edDispell -Naowh|r", [[Interface\Addons\SharedMedia\sound\Dispell -Naowh.ogg]])
LSM:Register("sound", "|cff0091edDodge Inc -Naowh|r", [[Interface\Addons\SharedMedia\sound\Dodge Inc -Naowh.ogg]])
LSM:Register("sound", "|cff0091edDodge -Naowh|r", [[Interface\Addons\SharedMedia\sound\Dodge -Naowh.ogg]])
LSM:Register("sound", "|cff0091edDot -Naowh|r", [[Interface\Addons\SharedMedia\sound\Dot -Naowh.ogg]])
LSM:Register("sound", "|cff0091edFixate -Naowh|r", [[Interface\Addons\SharedMedia\sound\Fixate -Naowh.ogg]])
LSM:Register("sound", "|cff0091edFrontal -Naowh|r", [[Interface\Addons\SharedMedia\sound\Frontal -Naowh.ogg]])
LSM:Register("sound", "|cff0091edHide -Naowh|r", [[Interface\Addons\SharedMedia\sound\Hide -Naowh.ogg]])
LSM:Register("sound", "|cff0091edHigh Stacks -Naowh|r", [[Interface\Addons\SharedMedia\sound\High Stacks -Naowh.ogg]])
LSM:Register("sound", "|cff0091edImmune -Naowh|r", [[Interface\Addons\SharedMedia\sound\Immune -Naowh.ogg]])
LSM:Register("sound", "|cff0091edIn -Naowh|r", [[Interface\Addons\SharedMedia\sound\In -Naowh.ogg]])
LSM:Register("sound", "|cff0091edInc -Naowh|r", [[Interface\Addons\SharedMedia\sound\Inc -Naowh.ogg]])
LSM:Register("sound", "|cff0091edInside -Naowh|r", [[Interface\Addons\SharedMedia\sound\Inside -Naowh.ogg]])
LSM:Register("sound", "|cff0091edIntermission -Naowh|r", [[Interface\Addons\SharedMedia\sound\Intermission -Naowh.ogg]])
LSM:Register("sound", "|cff0091edKick -Naowh|r", [[Interface\Addons\SharedMedia\sound\Kick -Naowh.ogg]])
LSM:Register("sound", "|cff0091edKnock -Naowh|r", [[Interface\Addons\SharedMedia\sound\Knock -Naowh.ogg]])
LSM:Register("sound", "|cff0091edLeft -Naowh|r", [[Interface\Addons\SharedMedia\sound\Left -Naowh.ogg]])
LSM:Register("sound", "|cff0091edLinked -Naowh|r", [[Interface\Addons\SharedMedia\sound\Linked -Naowh.ogg]])
LSM:Register("sound", "|cff0091edLoS -Naowh|r", [[Interface\Addons\SharedMedia\sound\LoS -Naowh.ogg]])
LSM:Register("sound", "|cff0091edLostVikings -Naowh|r", [[Interface\Addons\SharedMedia\sound\LongboatRaid.ogg]])
LSM:Register("sound", "|cff0091edMelee -Naowh|r", [[Interface\Addons\SharedMedia\sound\Melee -Naowh.ogg]])
LSM:Register("sound", "|cff0091edMove -Naowh|r", [[Interface\Addons\SharedMedia\sound\Move -Naowh.ogg]])
LSM:Register("sound", "|cff0091edNext -Naowh|r", [[Interface\Addons\SharedMedia\sound\Next -Naowh.ogg]])
LSM:Register("sound", "|cff0091edNuke -Naowh|r", [[Interface\Addons\SharedMedia\sound\Nuke -Naowh.ogg]])
LSM:Register("sound", "|cff0091edOrb -Naowh|r", [[Interface\Addons\SharedMedia\sound\Orb -Naowh.ogg]])
LSM:Register("sound", "|cff0091edOut -Naowh|r", [[Interface\Addons\SharedMedia\sound\Out -Naowh.ogg]])
LSM:Register("sound", "|cff0091edPersonal -Naowh|r", [[Interface\Addons\SharedMedia\sound\Personal -Naowh.ogg]])
LSM:Register("sound", "|cff0091edPot -Naowh|r", [[Interface\Addons\SharedMedia\sound\Pot -Naowh.ogg]])
LSM:Register("sound", "|cff0091edPull -Naowh|r", [[Interface\Addons\SharedMedia\sound\Pull -Naowh.ogg]])
LSM:Register("sound", "|cff0091edPush -Naowh|r", [[Interface\Addons\SharedMedia\sound\Push -Naowh.ogg]])
LSM:Register("sound", "|cff0091edRanged -Naowh|r", [[Interface\Addons\SharedMedia\sound\Ranged -Naowh.ogg]])
LSM:Register("sound", "|cff0091edReady -Naowh|r", [[Interface\Addons\SharedMedia\sound\Ready -Naowh.ogg]])
LSM:Register("sound", "|cff0091edReflect -Naowh|r", [[Interface\Addons\SharedMedia\sound\Reflect -Naowh.ogg]])
LSM:Register("sound", "|cff0091edRight -Naowh|r", [[Interface\Addons\SharedMedia\sound\Right -Naowh.ogg]])
LSM:Register("sound", "|cff0091edRun -Naowh|r", [[Interface\Addons\SharedMedia\sound\Run -Naowh.ogg]])
LSM:Register("sound", "|cff0091edShield -Naowh|r", [[Interface\Addons\SharedMedia\sound\Shield -Naowh.ogg]])
LSM:Register("sound", "|cff0091edSoak -Naowh|r", [[Interface\Addons\SharedMedia\sound\Soak -Naowh.ogg]])
LSM:Register("sound", "|cff0091edSpread -Naowh|r", [[Interface\Addons\SharedMedia\sound\Spread -Naowh.ogg]])
LSM:Register("sound", "|cff0091edStack -Naowh|r", [[Interface\Addons\SharedMedia\sound\Stack -Naowh.ogg]])
LSM:Register("sound", "|cff0091edStop -Naowh|r", [[Interface\Addons\SharedMedia\sound\Stop -Naowh.ogg]])
LSM:Register("sound", "|cff0091edStopcast -Naowh|r", [[Interface\Addons\SharedMedia\sound\Stopcast -Naowh.ogg]])
LSM:Register("sound", "|cff0091edSwitch -Naowh|r", [[Interface\Addons\SharedMedia\sound\Switch -Naowh.ogg]])
LSM:Register("sound", "|cff0091edTaunt -Naowh|r", [[Interface\Addons\SharedMedia\sound\Taunt -Naowh.ogg]])
LSM:Register("sound", "|cff0091edTotem -Naowh|r", [[Interface\Addons\SharedMedia\sound\Totem -Naowh.ogg]])
LSM:Register("sound", "|cff0091edTrap -Naowh|r", [[Interface\Addons\SharedMedia\sound\Trap -Naowh.ogg]])
LSM:Register("sound", "|cff0091edTurn -Naowh|r", [[Interface\Addons\SharedMedia\sound\Turn -Naowh.ogg]])
LSM:Register("sound", "|cff0091edLorgok Boss Dmg -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_BossDmg.ogg]])
LSM:Register("sound", "|cff0091edLorgok Burp -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_Burp.ogg]])
LSM:Register("sound", "|cff0091edLorgok Doesnt Happen -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_DoesntHappen.ogg]])
LSM:Register("sound", "|cff0091edLorgok Ejaculate -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_Ejaculate.ogg]])
LSM:Register("sound", "|cff0091edLorgok Help -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_Help.ogg]])
LSM:Register("sound", "|cff0091edLorgok Noooo -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_Noooo.ogg]])
LSM:Register("sound", "|cff0091edLorgok Oh What -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_OhWhat.ogg]])
LSM:Register("sound", "|cff0091edLorgok Ok Bro -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_OkBro.ogg]])
LSM:Register("sound", "|cff0091edLorgok Oribole -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_Oribole.ogg]])
LSM:Register("sound", "|cff0091edLorgok Stupid Dude -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_StupidDude.ogg]])
LSM:Register("sound", "|cff0091edLorgok WTF -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_WTF.ogg]])
LSM:Register("sound", "|cff0091edLorgok Yeah -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_Yeah.ogg]])
LSM:Register("sound", "|cff0091edLorgok Boss Dmg -Naowh|r", [[Interface\Addons\SharedMedia\sound\Lorgok_BossDmg.ogg]])


-- -----
--   STATUSBAR
-- -----
LSM:Register(MediaType_STATUSBAR, "Aluminium",			[[Interface\Addons\SharedMedia\statusbar\Aluminium]])
LSM:Register(MediaType_STATUSBAR, "Armory",				[[Interface\Addons\SharedMedia\statusbar\Armory]])
LSM:Register(MediaType_STATUSBAR, "BantoBar",			[[Interface\Addons\SharedMedia\statusbar\BantoBar]])
LSM:Register(MediaType_STATUSBAR, "Bars",				[[Interface\Addons\SharedMedia\statusbar\Bars]])
LSM:Register(MediaType_STATUSBAR, "Bumps",				[[Interface\Addons\SharedMedia\statusbar\Bumps]])
LSM:Register(MediaType_STATUSBAR, "Button",				[[Interface\Addons\SharedMedia\statusbar\Button]])
LSM:Register(MediaType_STATUSBAR, "Charcoal",			[[Interface\Addons\SharedMedia\statusbar\Charcoal]])
LSM:Register(MediaType_STATUSBAR, "Cilo",				[[Interface\Addons\SharedMedia\statusbar\Cilo]])
LSM:Register(MediaType_STATUSBAR, "Cloud",				[[Interface\Addons\SharedMedia\statusbar\Cloud]])
LSM:Register(MediaType_STATUSBAR, "Comet",				[[Interface\Addons\SharedMedia\statusbar\Comet]])
LSM:Register(MediaType_STATUSBAR, "Dabs",				[[Interface\Addons\SharedMedia\statusbar\Dabs]])
LSM:Register(MediaType_STATUSBAR, "DarkBottom",			[[Interface\Addons\SharedMedia\statusbar\DarkBottom]])
LSM:Register(MediaType_STATUSBAR, "Diagonal",			[[Interface\Addons\SharedMedia\statusbar\Diagonal]])
LSM:Register(MediaType_STATUSBAR, "Empty",			    [[Interface\Addons\SharedMedia\statusbar\Empty]])
LSM:Register(MediaType_STATUSBAR, "Falumn",				[[Interface\Addons\SharedMedia\statusbar\Falumn]])
LSM:Register(MediaType_STATUSBAR, "Fifths",				[[Interface\Addons\SharedMedia\statusbar\Fifths]])
LSM:Register(MediaType_STATUSBAR, "Flat",				[[Interface\Addons\SharedMedia\statusbar\Flat]])
LSM:Register(MediaType_STATUSBAR, "Fourths",			[[Interface\Addons\SharedMedia\statusbar\Fourths]])
LSM:Register(MediaType_STATUSBAR, "Frost",				[[Interface\Addons\SharedMedia\statusbar\Frost]])
LSM:Register(MediaType_STATUSBAR, "Glamour",			[[Interface\Addons\SharedMedia\statusbar\Glamour]])
LSM:Register(MediaType_STATUSBAR, "Glamour2",			[[Interface\Addons\SharedMedia\statusbar\Glamour2]])
LSM:Register(MediaType_STATUSBAR, "Glamour3",			[[Interface\Addons\SharedMedia\statusbar\Glamour3]])
LSM:Register(MediaType_STATUSBAR, "Glamour4",			[[Interface\Addons\SharedMedia\statusbar\Glamour4]])
LSM:Register(MediaType_STATUSBAR, "Glamour5",			[[Interface\Addons\SharedMedia\statusbar\Glamour5]])
LSM:Register(MediaType_STATUSBAR, "Glamour6",			[[Interface\Addons\SharedMedia\statusbar\Glamour6]])
LSM:Register(MediaType_STATUSBAR, "Glamour7",			[[Interface\Addons\SharedMedia\statusbar\Glamour7]])
LSM:Register(MediaType_STATUSBAR, "Glass",				[[Interface\Addons\SharedMedia\statusbar\Glass]])
LSM:Register(MediaType_STATUSBAR, "Glaze",				[[Interface\Addons\SharedMedia\statusbar\Glaze]])
LSM:Register(MediaType_STATUSBAR, "Glaze v2",			[[Interface\Addons\SharedMedia\statusbar\Glaze2]])
LSM:Register(MediaType_STATUSBAR, "Gloss",				[[Interface\Addons\SharedMedia\statusbar\Gloss]])
LSM:Register(MediaType_STATUSBAR, "Graphite",			[[Interface\Addons\SharedMedia\statusbar\Graphite]])
LSM:Register(MediaType_STATUSBAR, "Grid",				[[Interface\Addons\SharedMedia\statusbar\Grid]])
LSM:Register(MediaType_STATUSBAR, "Hatched",			[[Interface\Addons\SharedMedia\statusbar\Hatched]])
LSM:Register(MediaType_STATUSBAR, "Healbot",			[[Interface\Addons\SharedMedia\statusbar\Healbot]])
LSM:Register(MediaType_STATUSBAR, "Lyfe",				[[Interface\Addons\SharedMedia\statusbar\Lyfe]])
LSM:Register(MediaType_STATUSBAR, "LiteStep",			[[Interface\Addons\SharedMedia\statusbar\LiteStep]])
LSM:Register(MediaType_STATUSBAR, "LiteStepLite",		[[Interface\Addons\SharedMedia\statusbar\LiteStepLite]])
LSM:Register(MediaType_STATUSBAR, "Melli",				[[Interface\Addons\SharedMedia\statusbar\Melli]])
LSM:Register(MediaType_STATUSBAR, "Melli Dark",			[[Interface\Addons\SharedMedia\statusbar\MelliDark]])
LSM:Register(MediaType_STATUSBAR, "Melli Dark Rough",	[[Interface\Addons\SharedMedia\statusbar\MelliDarkRough]])
LSM:Register(MediaType_STATUSBAR, "Minimalist",			[[Interface\Addons\SharedMedia\statusbar\Minimalist]])
LSM:Register(MediaType_STATUSBAR, "Otravi",				[[Interface\Addons\SharedMedia\statusbar\Otravi]])
LSM:Register(MediaType_STATUSBAR, "Outline",			[[Interface\Addons\SharedMedia\statusbar\Outline]])
LSM:Register(MediaType_STATUSBAR, "Perl",				[[Interface\Addons\SharedMedia\statusbar\Perl]])
LSM:Register(MediaType_STATUSBAR, "Perl v2",			[[Interface\Addons\SharedMedia\statusbar\Perl2]])
LSM:Register(MediaType_STATUSBAR, "Pill",				[[Interface\Addons\SharedMedia\statusbar\Pill]])
LSM:Register(MediaType_STATUSBAR, "Rain",				[[Interface\Addons\SharedMedia\statusbar\Rain]])
LSM:Register(MediaType_STATUSBAR, "Rocks",				[[Interface\Addons\SharedMedia\statusbar\Rocks]])
LSM:Register(MediaType_STATUSBAR, "Round",				[[Interface\Addons\SharedMedia\statusbar\Round]])
LSM:Register(MediaType_STATUSBAR, "Ruben",				[[Interface\Addons\SharedMedia\statusbar\Ruben]])
LSM:Register(MediaType_STATUSBAR, "Runes",				[[Interface\Addons\SharedMedia\statusbar\Runes]])
LSM:Register(MediaType_STATUSBAR, "Skewed",				[[Interface\Addons\SharedMedia\statusbar\Skewed]])
LSM:Register(MediaType_STATUSBAR, "Smooth",				[[Interface\Addons\SharedMedia\statusbar\Smooth]])
LSM:Register(MediaType_STATUSBAR, "Smooth v2",			[[Interface\Addons\SharedMedia\statusbar\Smoothv2]])
LSM:Register(MediaType_STATUSBAR, "Smudge",				[[Interface\Addons\SharedMedia\statusbar\Smudge]])
LSM:Register(MediaType_STATUSBAR, "Steel",				[[Interface\Addons\SharedMedia\statusbar\Steel]])
LSM:Register(MediaType_STATUSBAR, "Striped",			[[Interface\Addons\SharedMedia\statusbar\Striped]])
LSM:Register(MediaType_STATUSBAR, "Tube",				[[Interface\Addons\SharedMedia\statusbar\Tube]])
LSM:Register(MediaType_STATUSBAR, "Water",				[[Interface\Addons\SharedMedia\statusbar\Water]])
LSM:Register(MediaType_STATUSBAR, "Wglass",				[[Interface\Addons\SharedMedia\statusbar\Wglass]])
LSM:Register(MediaType_STATUSBAR, "Wisps",				[[Interface\Addons\SharedMedia\statusbar\Wisps]])
LSM:Register(MediaType_STATUSBAR, "Xeon",				[[Interface\Addons\SharedMedia\statusbar\Xeon]])